'use strict';

export const LOAD_CONTRACT_TYPES_SUCCESS = 'LOAD_CONTRACT_TYPES_SUCCESS';

export const SET_CONTRACT_TYPE_ACTIVE_SUCCESS = 'SET_CONTRACT_TYPE_ACTIVE_SUCCESS';

export const CREATE_CONTRACT_TYPE_SUCCESS = 'CREATE_CONTRACT_TYPE_SUCCESS';
